export const database_options = [
  "MySQL",
  "Oracle Database",
  "Microsoft SQL Server",
  "PostgreSQL",
  "MongoDB",
  "SQLite",
  "IBM DB2",
  "Amazon Aurora",
  "MariaDB",
  "Redis",
  "CouchDB",
  "Apache Cassandra",
  "Neo4j",
  "Firebase Realtime Database",
  "Elasticsearch",
  "Microsoft Access",
  "Teradata",
  "Hadoop",
  "Amazon DynamoDB",
  "Apache Hive",
  "Apache HBase",
  "Google BigQuery",
  "Apache Kafka",
  "Apache Spark",
  "InfluxDB",
  "Memcached",
  "OrientDB",
  "ArangoDB",
  "Couchbase",
  "RavenDB",
  "FaunaDB",
  "TimescaleDB",
  "VoltDB",
  "MarkLogic",
  "Splunk",
  "Informix",
  "SAP HANA",
  "Apache Derby",
  "InterSystems Cache",
  "FileMaker Pro",
  "Virtuoso",
];

export const framework_options = [
  "Angular",
  "React",
  "Vue JS",
  "Ember JS",
  "Backbone JS",
  "Svelte",
  "Meteor",
  "Aurelia",
  "Polymer",
  "Mithril",
  "Preact",
  "Next JS",
  "Nuxt JS",
  "Gatsby",
  "Quasar Framework",
  "Bulma",
  "Tailwind CSS",
  "Bootstrap",
  "Foundation",
  "Material-UI",
  "Stencil",
  "Alpine JS",
  "Marko",
  "Riot JS",
  "Dojo Toolkit",
  "Choo",
  "Chakra UI",
  "Sencha Ext JS",
  "Ant Design",
  "PrimeReact",
  "Rebass",
  "Semantic UI",
  "UIKit",
  "Carbon Design System",
  "Shoelace",
  "Pure.css",
  "Milligram",
  "Skeleton",
  "Susy",
  "Cascade Framework",
  "Siimple",
  "Grommet",
  "React-Bootstrap",
  "Reactstrap",
  "Belle",
  "Blueprint",
  "Evergreen",
  "Quill",
  "Draft JS",
  "TinyMCE",
  "Froala Editor",
  "Django",
  "Ruby on Rails",
  "Laravel",
  "ASP.NET",
  "Symfony",
  "AdonisJS",
  "Phoenix",
  "Koa",
  "Gin",
  "Echo",
  "Sails JS",
  "CakePHP",
  "Slim",
  "Sinatra",
  "Ktor",
  "Vert.x",
  "Dropwizard",
  "Grails",
  "Nancy",
  "Scalatra",
  "Strapi",
  "LoopBack",
  "Actix",
  "Feathers",
  "NestJS",
  "Rocket",
  "Play Framework",
  "Pyramid",
  "Zope",
  "FastAPI",
  "Express JS",
  "Flask",
  "Hapi",
  "Spring Boot",
  "Framework7",
  "Appcelerator Titanium",
  "Ionic",
  "NativeScript-Vue",
  "SwiftUI",
  "Kotlin Multiplatform Mobile (KMM)",
  "Xamarin.Forms",
  "Cocos2d",
  "Kivy",
  "Corona SDK",
  "Intel XDK",
  "Marmalade SDK",
  "MoSync",
  "Flutter",
  "React Native",
  "Xamarin",
  "PhoneGap/Cordova",
  "NativeScript",
  "Adobe PhoneGap",
  "Unity",
  "Onsen UI",
  "Sencha Touch",
  "jQuery Mobile",
];
